export const LANDING_PAGE = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const HOME = '/home'
export const ACCOUNT = '/account'
export const ADD_ITEM = '/add-item'
export const ITEMS = '/items'
