export const WELCOME = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const HOME = '/home'
export const HOME_ACCOUNT = 'home/account'
export const ADMIN = '/admin'
export const PASSWORD_FORGET = '/pw-forget'
